name: erp_unified
description: "Unified College Academic Management System (CAMS) ERP Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.0
  flutter_localizations:
    sdk: flutter
  file_picker: ^5.3.0
  go_router: ^17.3.0
  flutter_riverpod: ^2.5.1
  fl_chart: ^1.2.0
  intl: ^0.20.2
  http: ^1.2.0
  month_year_picker: ^0.5.0+1
  loading_animation_widget: ^1.3.0
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.2
  supabase_flutter: ^2.6.0
  postgres: ^3.1.2
  data_table_2: ^2.7.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
