// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_web_plugins/flutter_web_plugins.dart' as flutter_web_plugins;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGFJPETW3rbUzPUveauQjC2sQl9GNYFxE',
    authDomain: 'parent-portal-c65ae.firebaseapp.com',
    projectId: 'parent-portal-c65ae',
    storageBucket: 'parent-portal-c65ae.firebasestorage.app',
    messagingSenderId: '470269747486',
    appId: '1:470269747486:web:36f68f3e7cdcd57053a90f',
  );
}
