// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // TODO: Add configurations for other platforms like Android and iOS if needed.
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ftQMYbKuIFJ-M8xK8gGpTQujH12HUYE',
    appId: '1:390398415824:web:7db5273fe959f792e71fd5',
    messagingSenderId: '390398415824',
    projectId: 'admin-portal-5bfb8',
    authDomain: 'admin-portal-5bfb8.firebaseapp.com',
    storageBucket: 'admin-portal-5bfb8.appspot.com',
    measurementId: 'G-N8L7YF28M5',
  );
}
